// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7x2ZZmu68TvjTnffhxbz5gAZMoO42l9A',
    appId: '1:549323466460:web:250a429baaf58e29833619',
    messagingSenderId: '549323466460',
    projectId: 'flutterfire-test-1c410',
    authDomain: 'flutterfire-test-1c410.firebaseapp.com',
    storageBucket: 'flutterfire-test-1c410.appspot.com',
    measurementId: 'G-LVFHFVXDPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxM9egXJohRqo9WV4PzA-LeinR-bgF82Q',
    appId: '1:549323466460:android:aec2a6237fe101c0833619',
    messagingSenderId: '549323466460',
    projectId: 'flutterfire-test-1c410',
    storageBucket: 'flutterfire-test-1c410.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnq-cSVJWXzjBBdG5DqCPZkmNHWkzTSCA',
    appId: '1:549323466460:ios:08d89e768750281f833619',
    messagingSenderId: '549323466460',
    projectId: 'flutterfire-test-1c410',
    storageBucket: 'flutterfire-test-1c410.appspot.com',
    iosBundleId: 'com.example.flutterFlutterfireExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnq-cSVJWXzjBBdG5DqCPZkmNHWkzTSCA',
    appId: '1:549323466460:ios:2baf254a99b1d542833619',
    messagingSenderId: '549323466460',
    projectId: 'flutterfire-test-1c410',
    storageBucket: 'flutterfire-test-1c410.appspot.com',
    iosBundleId: 'com.example.flutterFlutterfireExample.RunnerTests',
  );
}
